### ISSUE TITLE
Duplicate route detected on creating routes with different method

### ISSUE THREAD

**Issue by nitin-kakkar** [vincentsarago/lambda-proxy#29]
Hi

Firstly, thanks for this amazing library, saved us lot of time.

I am getting **Duplicate route detected error** when creating the routes as shown below. 
Since the methods are different , should these routes be considered different. If not, can you please suggest an alternative to handle this scenario.

@app.route('/create',methods = ['GET'])
def create_file():
    return func_get()

@app.route('/create', methods = ['POST'])
def create_file_form():
    return func_post()

**Comment by vincentsarago** [comment]
thanks for the issue @nitin-kakkar ,

Sadly your routes will be considered the same (there is no difference between post/get routes when it comes to route names.

you could do 
```
@app.route('/create',methods = ['GET',  'POST'])
def create_file(body):

# Here you can check the content of the `app.event["httpMethod"]` to see if it's GET or POST event if you need to handle those differently 

return func_post()
```

hope it helps
