### ISSUE TITLE
Custom cache control headers

### ISSUE THREAD

**Issue by kylebarron** [vincentsarago/lambda-proxy#32]
I'm testing out https://github.com/developmentseed/cogeo-mosaic-tiler/pull/2 with a `ttl` argument.

If `ttl` is not `None`, the returned `Cache-Control` header is `max-age={ttl}`.
https://github.com/vincentsarago/lambda-proxy/blob/abfcb4e12adefd196bdbe3732efacc15afb502a5/lambda_proxy/proxy.py#L577-L580

I'm trying to use Cloudflare to reduce my lambda and bandwidth costs. I believe that without the `public` keyword in the `Cache-Control` header, Cloudflare doesn't cache the item. For example, the response headers for
```
https://naip-lambda.kylebarron.dev/4c4d507790e8afa837215677bd6f74f58711bfaf3e1d5f7226193e12/14/2620/6332@2x
```
are:
```
access-control-allow-credentials: true
access-control-allow-methods: GET
access-control-allow-origin: *
cache-control: max-age=2592000
cf-cache-status: DYNAMIC
cf-ray: 57120388aecdf778-DEN
content-type: image/jpg
date: Mon, 09 Mar 2020 04:22:19 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
...
```
I believe that `cf-cache-status: DYNAMIC` means that Cloudflare [won't cache the item](https://support.cloudflare.com/hc/en-us/articles/200172516#h_bd959d6a-39c0-4786-9bcd-6e6504dcdb97). (For other items that I know Cloudflare is caching; the response is always either `MISS` or `HIT`).

Thus, I'd like to add functionality for custom cache-control headers. Could it be an arbitrary string used instead of `ttl`?

**Comment by vincentsarago** [comment]
sure do it !
