### ISSUE TITLE
add documentation or ways to deploy lambda + API Gateway 

### ISSUE THREAD

**Issue by vincentsarago** [vincentsarago/lambda-proxy#33]

**Comment by simith** [comment]
Please can you provide documentation for ways to deploy lambda + API Gateway using this framework

**Comment by sp4ce** [comment]
Please can you provide documentation about how to deploy the lambda? I am not sure about this, but usually in our lambda we have a entry point handler method, where would it be with the `@APP` annotation ?

**Comment by vincentsarago** [comment]
👋 FYI this project is slowly but surely going to be deprecated as we move to FastAPI + Mangum which are way better than this hacky library. 

there is no proper documentation for how to deploy the lambda because there are plenty of ways to do it. BUT I would suggest to checkout some on the repo that are using lambda-proxy: 

https://github.com/vincentsarago/lambda-proxy/network/dependents?package_id=UGFja2FnZS01MjI1NzczNA%3D%3D
