### ISSUE TITLE
Multi-method routes don't work as described in examples

### ISSUE THREAD

**Issue by kelsta** [vincentsarago/lambda-proxy#42]
I'm attempting to implement a route which returns an object listing for `GET` requests, creating new objects when receiving a `POST`.

The examples show the implementation of such a multi-method route as:

```python
@APP.route("/add", methods=["GET", "POST"], cors=True)
def post(body) -> Tuple[str, str, str]:
    """Return JSON Object."""
    return ("OK", "text/plain", body)
```

However that implementation doesn't seem to work as expected. The `body` argument is only added to the kwargs dict when the method is `POST`, so `GET` requests to the route fail with the error `missing 1 required positional argument: 'body'`.

I've tried several ways around this, but each seems to have drawbacks.

- Setting a default value for the `body` argument eg. `python
def post(body=None) -> Tuple[str, str, str]`. However this results in `body` being listed as a parameter in the generated docs for the GET request, which isn't really the case.
- Defining that function with the signature `def post(**kwargs)` and pulling the body from kwargs when it's present — but that results in the generated documentation listing `kwargs` as a parameter of the route.
- Defining multiple routes with the same path `/add`, but differing methods. This doesn't work as an exception is raised as they're detected as being duplicate routes.

Please do let me know if I've missed something obvious — it doesn't seem clear what the intended way to define these multi-method routes is intended to be.

**Comment by vincentsarago** [comment]
@kelsta Thanks for opening this issue. 

```
The body argument is only added to the kwargs dict when the method is POST, so GET requests to the route fail with the error missing 1 required positional argument: 'body'.
```

When you are calling `/add` do you pass `?body=something` as a  query params ?

**Comment by kelsta** [comment]
No there's no querystring parameters on either the `GET` or `POST` request.

The `body` I refer to is the attribute extracted from the API Gateway event on a `POST` request as at https://github.com/vincentsarago/lambda-proxy/blob/a21343e9a73f9413ebd821a51f823973df333946/tests/test_proxy.py#675

**Comment by vincentsarago** [comment]
well then I'm not sure to understand what you are trying to do.

You want to add a `/add` route with the `GET` method without passing any info?

**Comment by kelsta** [comment]
Thanks for the quick replies Vincent!

Sorry for the confusion, my route isn't actually named `/add` - that's just the one I pulled from the examples and used here for clarity. I think I've misunderstood what you intend so show with that spcific example as I'd not considered you would intend to create a record from a `GET` request, as they're normally considered idempotent. I thought the example was trying to show my use case - create on `POST` and list on `GET`.

But my routes are for example names things like `/people`, `/places`, `/things`.

So for example I want a `GET` request to `/people` to get a list of the people from the system. And a `POST` request to `/people` (with an appropriate JSON body) to create a new person in the system. Using the standard RESTful verbs pattern for getting and creating those entities through the API.

**Comment by vincentsarago** [comment]
@kelsta make sense, I totally get it.
Let me see if I can update the way we add routes.

**Comment by vincentsarago** [comment]
would a solution where you have:

```python
@APP.route("/people", methods=["POST"], cors=True)
def add_people(body) -> Tuple[str, str, str]:    

@APP.route("/people", methods=["GET"], cors=True)
def list_people() -> Tuple[str, str, str]: 
```
works ?

**Comment by kelsta** [comment]
Great, thanks. Yes that's exactly one of the things I tried initially.

It feels like it makes sense for routes to actually be unique based on a combination of `path` + `method`?

With separate definitions having different methods, but the same path as above, it'd allow separate descriptions for the documentation too, which seems nice as they do different things.

One minor issue I see is that it'd be possible to apply different `tag` lists to endpoints with the same `path`, which could be quite confusing.

**Comment by vincentsarago** [comment]
> It feels like it makes sense for routes to actually be unique based on a combination of path + method?

Yes

> One minor issue I see is that it'd be possible to apply different tag lists to endpoints with the same path, which could be quite confusing.

Yes, but the user will have to be smart then 😄

**Comment by vincentsarago** [comment]
I think #43 should fix it, would be great if you could test is because I make the release (`5.2.0`) @kelsta

**Comment by kelsta** [comment]
Fantastic, thanks Vincent. That seems to work perfectly for me.
